image: kasproject/kas-isar:latest

all:
  stage: build
  script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - source isar-init-build-env out
    - bitbake
        multiconfig:qemuarm-wheezy:isar-image-base
        multiconfig:qemuarm-jessie:isar-image-base
        multiconfig:qemuarm-stretch:isar-image-base
        multiconfig:qemuarm64-stretch:isar-image-base
        multiconfig:qemui386-jessie:isar-image-base
        multiconfig:qemui386-stretch:isar-image-base
        multiconfig:qemuamd64-jessie:isar-image-base
        multiconfig:qemuamd64-stretch:isar-image-base
        multiconfig:rpi-jessie:isar-image-base
