image: kasproject/kas-isar:latest

variables:
  GIT_STRATEGY: clone

all:
  stage: build
  script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - scripts/ci_build.sh -q -f
